### ISSUE TITLE
Adjust lightning ellipsoid

### ISSUE THREAD

**Issue by deeplycloudy** [deeplycloudy/glmtools#14]
An update the ground system is pending that will adjust the lightning ellipsoid definition in order to optimize ground-referenced location accuracy in the GLM L2 data. Therefore, the lightning ellipsoid removal function in `glmtools` needs to be adjusted to give correct fixed grid coordinates.

Right now the parameters to the lightning ellipsoid correction function are:

       re_ltg_ellps=6.394140e6, rp_ltg_ellps = 6.362755e6,
       re_grs80 = 6.378137e6, rp_grs80 = 6.35675231414e6,
       sat_grs80_height=35.786023e6

The new values should be `re_ltg_ellps = re_grs80 + 14.0e3` and `rp_ltg_ellps = rp_grs80 + 6.0e3`.

This means no change to the polar altitude. The equatorial altitude is reduced 2 km from 16 km.

Proposed change is to:
1. Change defaults to match the new lightning ellipsoid definition.
2. Have the gridding code examine the date, and use the old GLM ellipsoid height if data prior to the change are being used.

For real-time applications, 1. is the only truly necessary change, since a real-time system will not encounter old data.

**Comment by deeplycloudy** [comment]
Complete in PR #16

**Comment by jlc248** [comment]
Eric, just to clarify for my sake, if I am not using the code from PR #16 in realtime starting Oct.15, then my lightning geolocation will be off a bit. I will try to implement the PR soon, but do you have a ballpark estimate of how wrong the geolocation would be?
