### ISSUE TITLE
Total energy

### ISSUE THREAD

**Issue by jlc248** [deeplycloudy/glmtools#15]
Per our conversation, you said that total energy is not in "per flash" units. I now know why I thought it was, per the metadata:

float total_energy(ntimes, nx, ny) ;
		total_energy:long_name = "Total radiant energy" ;
		**total_energy:units = "J per flash" ;**
		total_energy:grid_mapping = "goes_imager_projection" ;
		total_energy:missing_value = -9999.f ;

 Not sure why I missed that this morning.

I think it would be good to just say "Joules" here.

**Comment by jlc248** [comment]
This was a copy and paste from an ncdump of a *dx_total_energy.nc file.

**Comment by deeplycloudy** [comment]
Thanks for this report, and I see why you thought what you did. Your proposed fix is the correct language, and I'm going to use this as an opportunity to write a formal unit test to check for energy conservation.

**Comment by deeplycloudy** [comment]
An ad-hoc check shows that the energy calculation was being done correctly and in the units you stated.

**Comment by deeplycloudy** [comment]
This fix is part of #18, which is already on the ugf-newgrid branch. That branch is the future of glmtools, so closing this.
