### ISSUE TITLE
parallax correction in flash centroid density?

### ISSUE THREAD

**Issue by jlc248** [deeplycloudy/glmtools#17]
There appears to be a parallax correction in the flash centroid density field, that does not appear to be in the other fields, (e.g. flash extent density). Modifying a tutorial in glmtools, I made images for FCD and FED for a random time. I think it perhaps shows that the FCD is not getting parallax-corrected. 

Here is the base make_GLM_grids.py call:
```python glmtools/examples/grid/make_GLM_Grids.py -o outdata --fixed_grid --split_events --goes_position=east --goes_sector=conus --dx=2.0 --dy=2.0 <files>"```

Here are a couple of images. It helps to toggle between the images. Do you think there is a correction here that was supposed to be uncorrected, like the other fields?

![outdataglm_flash_extent_2018-08-12_215900](https://user-images.githubusercontent.com/19976290/44037767-ca475cb0-9eda-11e8-95ae-6748d913fc60.png)
![outdataglm_flash_init_2018-08-12_215900](https://user-images.githubusercontent.com/19976290/44037769-ca631126-9eda-11e8-96ea-f833aed99c49.png)

**Comment by deeplycloudy** [comment]
Yeah, it looks like the centroids are shifted to the SE, which means that they might not be getting corrected back to the fixed grid properly. Thanks for the report.

**Comment by deeplycloudy** [comment]
This has been fixed on the correctflgrcentroids branch and that branch has been merged into all the downstream branches (see https://github.com/deeplycloudy/glmtools/network).

**Comment by jlc248** [comment]
Awesome...thank you!

**Comment by deeplycloudy** [comment]
Closing since the correctflgrcentroids branch is now merged into master.
