### ISSUE TITLE
Wrong units or values in average flash area?

### ISSUE THREAD

**Issue by jlc248** [deeplycloudy/glmtools#24]
Hello,

I am finding the values to be very large for the output average flash area (~10^8 km^2). I tested this out with the latest master and unifiedgridfile branches.

For example,
`make_GLM_grids.py -o stuff --fixed_grid --split_events --goes_position east --goes_sector conus --dx=2.0 --dy=2.0 OR_GLM-L2-LCFA_G16_s20190521946*`

Are these the correct values but expressed simply in m^2?

**Comment by deeplycloudy** [comment]
Yes, that sounds right. Oddly, I thought I fixed this on unifiedgridfile in this commit. The problem is the ground system changed the units in L2 at some point, so I modify the units in the L2 data when I read it in.

https://github.com/deeplycloudy/glmtools/commit/4e9a4425b09fe758b750e9ee99604ab9cdb7a2c0

**Comment by deeplycloudy** [comment]
Elaborating on the above, it looks to me like your unifiedgridfile might somehow not be current, or else something really odd is going on.

I just tried the dataset you mentioned, and got 

```
In [1]: import xarray as xr                                                                                                                                                   

In [2]: d=xr.open_dataset('/Users/ebruning/Downloads/2019/Feb/21/OR_GLM-L2-GLMC-M3_G16_s20190521946000_e20190521947000_c20190522017080.nc')                                   

In [3]: d.average_flash_area.min()                                                                                                                                            
Out[3]: 
<xarray.DataArray 'average_flash_area' ()>
array(68., dtype=float32)

In [4]: d.average_flash_area.max()                                                                                                                                            
Out[4]: 
<xarray.DataArray 'average_flash_area' ()>
array(910., dtype=float32)
```

I confirmed that the patch in the commit mentioned above was working for me. Compare the ncdump vs. the GLMDataset reader:
```
ncdump -h /Users/ebruning/Downloads/OR_GLM-L2-LCFA_G16_s20190521946000_e20190521946200_c20190521946223.nc | grep area
<snip>
		flash_area:scale_factor = 152601.9f ;
		flash_area:add_offset = 0.f ;
		flash_area:units = "m2" ;
```

```
In [3]: glm = GLMDataset('/Users/ebruning/Downloads/OR_GLM-L2-LCFA_G16_s20190521946000_e20190521946200_c20190521946223.nc')                                                   

In [4]: glm.dataset.flash_area                                                                                                                                                
Out[4]: 
<xarray.DataArray 'flash_area' (number_of_flashes: 575)>
array([155.04349, 301.5413 , 969.6322 , ..., 346.86404, 546.00946, 152.29666],
      dtype=float32)
In [6]: glm.dataset.flash_area.attrs                                                                                                                                          
Out[6]: OrderedDict([('units', 'km2')])
```

**Comment by jlc248** [comment]
I re-checked installed unifiedgridfile branch from scratch and not it works as intended. Not sure what happened. Thank you for suffering my incompetence!

**Comment by deeplycloudy** [comment]
No worries! Nice to have this in the tracker in case anyone else runs into it.
