### ISSUE TITLE
Output grid filenames for GOES-West say G16

### ISSUE THREAD

**Issue by deeplycloudy** [deeplycloudy/glmtools#26]
On the unifiedgridfile branch, the grid  filenames still say G17 even when gridding GOES-West data.

**Comment by djhoese** [comment]
Where are these filenames generated? If you can point me to the code I can see what I can do.

**Comment by deeplycloudy** [comment]
See the half dozen lines starting here: https://github.com/deeplycloudy/glmtools/blob/ugf-newgrid/glmtools/io/imagery.py#L486
