### ISSUE TITLE
Bug in mimic_lma.py

### ISSUE THREAD

**Issue by tjlang** [deeplycloudy/glmtools#45]
Line 1033 in io/mimic_lma.py:
        fl_chunks = (d['flash'][0] for d in fake_lma)

Should not have 0 as the index, it should be 1 instead. i.e.,
        fl_chunks = (d['flash'][1] for d in fake_lma)

Otherwise, the GLM gridding in examples/glm_lma_param_space.sh will fail. This is because in the current code ev_chunks (line 1032) and fl_chunks get set to the same tuple, and they shouldn't be. This was a hard bug to track down because the exception failure ends up occurring in a different function, so trackback wasn't very elucidating.

**Comment by deeplycloudy** [comment]
So that I can match line numbers, is this on master? 

I haven't used that script in a long while, and if you're using it to grid to lat, lon instead of fixed grid that code path is largely untested.

**Comment by tjlang** [comment]
Yes.

**Comment by deeplycloudy** [comment]
Thanks for the report, @tjlang! It's been fixed as recommended.
