### ISSUE TITLE
Flash "initiation" density

### ISSUE THREAD

**Issue by jlc248** [deeplycloudy/glmtools#5]
`examples/grid/make_GLM_grids.py` creates numerous gridded GLM fields. Among these, is a flash "initiation" density field.

The developer has informed me that this is actually a flash centroid density grid. The output filename needs to be changed, (I recommend something like, "GLM-00-00_20180622_150000_180_1src_280urad-dx_flash_centroid.nc"). Within the netCDF, the long_name attribute of  the flash_centroid_density variable needs to be changed from "Flash initiation density" to "Flash centroid density".

**Comment by deeplycloudy** [comment]
Thanks for the proposal for a fix to this. Sounds like a good approach. As noted in #9, this falls under a larger need to standardize names and file formats for consistency with the field names being used in the US National Weather Service.

**Comment by deeplycloudy** [comment]
Closing, as this fix is part of the ugf-newgrid branch that will become the new default file format and variable names.
