### ISSUE TITLE
Create single netcdf output file

### ISSUE THREAD

**Issue by djhoese** [deeplycloudy/glmtools#52]
I'm following the README and docs and try running commands like:

```
python make_GLM_grids.py -o /path/to/output/ --fixed_grid --split_events \
--goes_position east --goes_sector conus --dx=2.0 --dy=2.0
--start=2018-01-04T05:37:00 --end=2018-01-04T05:38:00 \
OR_GLM-L2-LCFA_G16_s20180040537000_e20180040537200_c20180040537226.nc
```

But I get one file per variable it seems. How can I create the single NetCDF files like those available on the unidata thredds server? I'm sure I missed something obvious.

**Comment by deeplycloudy** [comment]
@djhoese use the ugf-newgrid branch to create unified files. To run it you'l need the minvaluegrids branch of lmatools.

**Comment by djhoese** [comment]
:man_facepalming: I must have typed the branch name wrong. I thought I was already using the `ugf-newgrid` branch but was apparently on master. Thanks.
