### ISSUE TITLE
small typo in install docs

### ISSUE THREAD

**Issue by jhamman** [deeplycloudy/glmtools#6]
In https://github.com/deeplycloudy/glmtools/blob/master/docs/index.rst#installation, the xarray version  is specified as "xarray >= 0.97". It should probably read 0.9.7.

**Comment by deeplycloudy** [comment]
Thanks for catching this, and I agree. Do you want to submit a PR, or shall I fix it?

**Comment by jhamman** [comment]
I'll let you do it 😉

**Comment by deeplycloudy** [comment]
Fixed with https://github.com/deeplycloudy/glmtools/commit/3547ed10995e98f259da685f3970ec1ff74ef7a5
