### ISSUE TITLE
glmProcess.sh: 16: /glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc: Directory nonexistent

### ISSUE THREAD

**Issue by hproe** [deeplycloudy/glmtools#80]
From the script `glm_lma_param_space.sh` I have extracted the part that processes GLM flshes to grid like

```
export MPLBACKEND="Agg"
export GLMGRIDSCRIPT=~/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py
export GLMSORTGRID=./GLM/
export CTRLAT=33.5
export CTRLON=-101.5
export WIDTH=800
export GLMFILES=~/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc
echo "Processing GLM flashes to grid"
for GLMEVENTS in 1 #2 4
do
    python $GLMGRIDSCRIPT \
>        -o $GLMSORTGRID \
>        --nevents $GLMEVENTS \
>        --ctr_lat $CTRLAT --ctr_lon $CTRLON --width $WIDTH --height $WIDTH \
>        $GLMFILES &
done
```

When I run this as `glmProcess.sh` in glmval environment with the test LCFA files  I get

`glmProcess.sh: 16: .../glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc: Directory nonexistent`
I can manually cd to this directory and get to the files ok. What is going on here?

**Comment by djhoese** [comment]
Do an `echo $GLMFILES`. My guess is you either have a bash array variable that isn't being expanded or glmtools can't handle the `~` in the path.

**Comment by hproe** [comment]
Okay, the ~ was a problem. But now I hit on an indexing issue as below
```
(glmval) hp@AORUS:~$ sh glmProcess.sh
Processing GLM flashes to grid
(glmval) hp@AORUS:~$ Traceback (most recent call last):
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 326, in <module>
    gridder, glm_filenames, start_time, end_time, grid_kwargs = grid_setup(args)
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 175, in grid_setup
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 175, in <listcomp>
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/glmtools/glmtools/io/glm.py", line 41, in parse_glm_filename
    algorithm = parts[1]
IndexError: list index out of range

```

**Comment by djhoese** [comment]
What do your full filenames look like and where did you get the files from? It would seem glmtools doesn't know how to parse the filename.

**Comment by hproe** [comment]
The LCFA files are those that come with the glmtools package with full names like
`OR_GLM-L2-LCFA_G16_s20181830433200_e20181830433400_c20181830433424.nc`
In the shell script they get called as follows
`export GLMFILES=/home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183043*.nc`
I have checked the parsing of the filename by injecting it directly to the function `def parse_glm_filename()` - no problem as expected.
It looks like in the shell script, somehow, the filename doesn't make it to this function.
I have tried to give to `GLMFILES` only a single (full) name, but also here I get the `list index out of range` error.
Looks like there is a problem with the list carried by `GLMFILES`.

**Comment by hproe** [comment]
Looks like the problem comes from the filename array that is handed down to the function `parse_glm_filename` in `make_GLM_grids.py`:

```
        filename_parser = parse_glm_filename
        start_idx = 3
        end_idx = 4

    glm_filenames = args.filenames
    base_filenames = [os.path.basename(p) for p in glm_filenames]
    try:
```
But I cannot se what could go wrong here.

**Comment by djhoese** [comment]
If you print `glm_filenames` in that code you just pasted, what do you get? Did you ever do that `echo ` (in bash) of your filename variable?

**Comment by hproe** [comment]
I have tried `echo base_filenames` (also with leading $) after `base_filename = ...` but in both cases I get: 

```
base_filenames
                      ^
SyntaxError: invalid syntax

Mayb print would do, bt how do I get the output in the terminal
```

**Comment by djhoese** [comment]
In **BASH**

I was hoping you could print (echo) your bash variable. The one you set here:

```
export GLMFILES=~/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc
echo $GLMFILES
```

In python I was saying you should do:

```
print(glm_filenames)
```

**Comment by hproe** [comment]
Yes, I have done the echo and print, respectively. I forgot to tell you that the echo shows the filename array, fine, but what I overlooked is that the array also contains, at the top of the list, the wild-card item from $GLMFILES . I tried then to eliminate it with the code line `glm_filenames=glm_filenames[1:]` in `maske_GLM_grids.py` like
   ```
 glm_filenames = args.filenames
    glm_filenames=glm_filenames[1:]
    base_filenames = [os.path.basename(p) for p in glm_filenames]
```
But I continue to get the out-of index error. I do not understand this - looking in example in github $GLMFILES is also defined with a wildcard.
BTW the `print(glm-filename)` does not print anything and again I get the out-of-index error.

**Comment by djhoese** [comment]
Could you please show the output of the `echo` and the `print`? If `GLMFILES` includes the wildcard pattern then something is not right. Also check your `print`, you have a `-` instead of `_` and you're missing the `s` at the end of the variable name. You said `print(glm_filenames)` prints nothing, but that means it is `None` which means the script isn't getting anything that it considers a filename argument.

**Comment by hproe** [comment]
Sorry, not copy/pasting from the script I mistyped the print statement  in my former note, i.e. I used it as given by you. However, as alrerady said it does not output something. Actually, also printing a text string like `print("blabla")` does not print at all.
About the wildcard pattern see script and output below. As you see there it does not even work when passing a single file with full name. So the $GLMFILES information is not passed along correctly irrespective of specifying wildcard or not. I really wonder what goes on here.
I would really like to have a working gridding script  that brings me forward in my case studies with the combination of TOE/FED with ABI composites. Do you have/now alternative ways to grid the LCFA files?

```
SCRIPT calling LCFA infor with wildcard or (outcommented) or single file with full name 

export MPLBACKEND="Agg"
export GLMGRIDSCRIPT=/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py
export GLMSORTGRID=./GLMGLMGLM/
export CTRLAT=33.5
export CTRLON=-101.5
export WIDTH=800
export GLMFILES=/home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc
#export GLMFILES=/home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s20181830433000_e20181830433200_c20181830433231.nc
echo "Processing GLM flashes to grid"
echo $GLMFILES
for GLMEVENTS in 1 #2 4
do
    python $GLMGRIDSCRIPT \
>        -o $GLMSORTGRID \
>        --nevents $GLMEVENTS \
>        --ctr_lat $CTRLAT --ctr_lon $CTRLON --width $WIDTH --height $WIDTH \
>        $GLMFILES &
done


OUTPT wildcard

glm) hp@AORUS:~/Documents/pythonScripts/glmtools/examples$ sh glmProcess.sh
Processing GLM flashes to grid
/home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s2018183*.nc /home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s20181830433000_e20181830433200_c20181830433231.nc /home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s20181830433200_e20181830433400_c20181830433424.nc /home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s20181830433400_e20181830434000_c20181830434029.nc
(glm) hp@AORUS:~/Documents/pythonScripts/glmtools/examples$ Traceback (most recent call last):
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 329, in <module>
    gridder, glm_filenames, start_time, end_time, grid_kwargs = grid_setup(args)
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 178, in grid_setup
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 178, in <listcomp>
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/glmtools/io/glm.py", line 41, in parse_glm_filename
    algorithm = parts[1]
IndexError: list index out of range

OUTPUT single files

(glm) hp@AORUS:~/Documents/pythonScripts/glmtools/examples$ sh glmProcess.sh
Processing GLM flashes to grid
/home/hp/Documents/pythonScripts/glmtools/glmtools/test/data/OR_GLM-L2-LCFA_G16_s20181830433000_e20181830433200_c20181830433231.nc
(glm) hp@AORUS:~/Documents/pythonScripts/glmtools/examples$ Traceback (most recent call last):
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 329, in <module>
    gridder, glm_filenames, start_time, end_time, grid_kwargs = grid_setup(args)
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 178, in grid_setup
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/examples/grid/make_GLM_grids.py", line 178, in <listcomp>
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/glmtools/io/glm.py", line 41, in parse_glm_filename
    algorithm = parts[1]
IndexError: list index out of range
```

**Comment by djhoese** [comment]
FYI There are existing glmtools output files here: https://thredds.unidata.ucar.edu/thredds/catalog/satellite/goes/east/products/GeostationaryLightningMapper/CONUS/catalog.html

Note I am note @deeplycloudy who is the maintainer of this project.

What if you provide the filename directly inside the for loop (replace GLMFILES with the single filename)? It seems like your filenames are not properly getting to the script (as you said). So something must be wrong with your bash script. Maybe it needs a `;` somewhere, or an extra `\`, or the `#` comment in your for loop is messing things up. I'm not sure. I don't see anything wrong with your filenames. The fact that a print inside the python code doesn't show up is not a good sign. Makes me think you aren't actually running the glmtools you think you are running, but the traceback suggests you are.

**Comment by deeplycloudy** [comment]
Thanks @djhoese for your help diagnosing this to date. I agree, the lack of any output from the print statements is strange, and it suggests something funny is happening in the shell script.

If instead you use one of the examples in the [documentation](https://github.com/deeplycloudy/glmtools/blob/master/docs/index.rst), does it work? The script you are building from is pretty old and doesn't have some of the other command line arguments that we've added since then, and those arguments are really the only calling path that has been tested much. Try the command below, instead.

```
python make_GLM_grids.py
--fixed_grid --split_events \
--goes_position east --goes_sector conus \
--dx=2.0 --dy=2.0 \
OR_GLM-L2-LCFA_G16_s20181830433000_e20181830433200_c20181830433231.nc \
OR_GLM-L2-LCFA_G16_s20181830433200_e20181830433400_c20181830433424.nc \
OR_GLM-L2-LCFA_G16_s20181830433400_e20181830434000_c20181830434029.nc
```

**Comment by hproe** [comment]
Thanks guys. Finally Eric has brought on the good track. Using his short script (which produces the same indexing error, not surprising when you read to the end), I get output from `print()`. In `make_GLM_grids.py` I am printing `base_ffilenames` here
```
    else:
        filename_parser = parse_glm_filename
        start_idx = 3
        end_idx = 4

    glm_filenames = args.filenames
    glm_filenames=glm_filenames[1]
    base_filenames = [os.path.basename(p) for p in glm_filenames]
    print('HERE WE GO           ',base_filenames) #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    try:
```
and watch what happens hen calling Eric's script:
```
(glm) hp@AORUS:~/Documents/pythonScripts/glmtools/examples/grid$ python make_GLM_grids.py --fixed_grid --split_events --goes_position east --goes_sector conus --dx=2.0 --dy=2.0 OR_GLM-L2-LCFA_G16_s20181830433000_e20181830433200_c20181830433231.nc OR_GLM-L2-LCFA_G16_s20181830433200_e20181830433400_c20181830433424.nc OR_GLM-L2-LCFA_G16_s20181830433400_e20181830434000_c20181830434029.nc
HERE WE GO          
  ['O', 'R', '_', 'G', 'L', 'M', '-', 'L', '2', '-', 'L', 'C', 'F', 'A', '_', 'G', '1', '6', '_', 's', '2', '0', '1', '8', '1', '8', '3', '0', '4', '3', '3', '2', '0', '0', '_', 'e', '2', '0', '1', '8', '1', '8', '3', '0', '4', '3', '3', '4', '0', '0', '_', 'c', '2', '0', '1', '8', '1', '8', '3', '0', '4', '3', '3', '4', '2', '4', '.', 'n', 'c']
Traceback (most recent call last):
  File "make_GLM_grids.py", line 329, in <module>
    gridder, glm_filenames, start_time, end_time, grid_kwargs = grid_setup(args)
  File "make_GLM_grids.py", line 178, in grid_setup
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "make_GLM_grids.py", line 178, in <listcomp>
    filename_infos = [filename_parser(f) for f in base_filenames]
  File "/home/hp/Documents/pythonScripts/glmtools/glmtools/io/glm.py", line 41, in parse_glm_filename
    algorithm = parts[1]
IndexError: list index out of range
```
No wonder decoding fails. `glm_filename` is still okay - it is the extraction of the `base_filenames` fails miserably. Cannot see what could go wrong here though.

Anyway, I think from here on I should find my way, including processing a gammut of LCFA files with wildcard.

**Comment by deeplycloudy** [comment]
The line `glm_filenames=glm_filenames[1]` is not part of the original `make_GLM_grids.py` script. It should be removed, or replaced with `[glm_filenames[1]]` to ensure that `glm_filenames` remains a list. As you have it above, it makes glm_filenames a string instead of a list, so the `base_filenames` line loops over each character in the string instead of each filename in the list.

**Comment by hproe** [comment]
Sorry, my bad. I have reinstalled glmtools  because I noted that also the LCFA sample files were corrupted. Now `make_GLM_grids.py` work flawless, also with LCFA wildcard files.Thnaks for the support.
